---
name: deploy-hs
dependencies: base >= 4.7 && < 5
library:
  source-dirs: src
tests:
  deploy-hs-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies:
      - deploy-hs
      - hspec
      - amazonka
      - lens
      - text
      - amazonka-core
      - amazonka
