---
name: deploy-hs
dependencies: base >= 4.7 && < 5

executables:
  app:
    main: Main.hs
    source-dirs: app
    dependencies:
      - deploy-hs
      - hspec
      - text
      - lens
      - amazonka
      - amazonka-core
      - amazonka-ec2

library:
  source-dirs: src
  dependencies:
    - lens
    - text
    - amazonka
    - amazonka-core
    - amazonka-ec2

tests:
  deploy-hs-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies:
      - deploy-hs
      - hspec
      - text
      - lens
      - amazonka
      - amazonka-core
      - amazonka-ec2
