#!/usr/bin/env bash
terraform output -raw private_key > ~/.ssh/mod4project
chmod 0600 ~/.ssh/mod4project
ssh-add ~/.ssh/mod4project
ssh -AJ ec2-user@"$(terraform output -raw public_instance_ip)" \
  ec2-user@"$(terraform output -raw private_instance_ip)"

