#!/usr/bin/env bash
set -euo pipefail

echo "ERROR: Not implemented! Failing fast!" >&2
exit 1

# Run the tests
cd tests && go test .; cd -

# Build the AMI
cd packer && packer build .; cd -

# Provision the infrastructure
cd terraform && terraform apply; cd -

# Ping the instances with ansible
cd ansible && ansible-playbook; cd -
